### ISSUE TITLE
ReadMe.md file needs update

### ISSUE THREAD

**Issue by sourish-cmi** [xKDR/CRRao.jl#148]
**Describe the bug**
ReadMe.md file needs update - the stable version should be 0.1.1

**To Reproduce**
1. Go to 'https://github.com/xKDR/CRRao.jl'
2. On the top page you can see the error that stable version is 0.1.0 - it should be 0.1.1

**Expected behavior**
### For version 0.1.1 (stable)
using Pkg; Pkg.add("CRRao")

**Comment by Nandini-Jaiswal** [comment]
@ShouvikGhosh2048, the readme doc also says:

---

### For version 0.1.1 (under development)
```Julia
using Pkg; Pkg.add(url = "https://github.com/xKDR/CRRao.jl.git")
```

---

Should we change anything here?

**Comment by sourish-cmi** [comment]
Add this YouTube link on introduction to CRRao 

https://www.youtube.com/live/XIXdO8vNCh4?si=_RXyu47JTSX1TVKh
