### ISSUE TITLE
Urgent: Revert to `fit` from `@fitmodel`

### ISSUE THREAD

**Issue by sourish-cmi** [xKDR/CRRao.jl#39]
Dear @ShouvikGhosh2048 can you please revert to `fit` from current `@fitmodel`?

This is a bit urgent. Please take it as the top priority.

@ayushpatnaikgit @ajaynshah @codetalker7

**Comment by ShouvikGhosh2048** [comment]
[PR to change fitmodel to fit](https://github.com/xKDR/CRRao.jl/pull/40)

**Comment by sourish-cmi** [comment]
A test for should be :

```Julia
using CRRao, RDatasets, StatsPlots, Plots, StatsModels
mtcars = dataset("datasets", "mtcars")

model = fit(MPG ~ HP + log(WT) + Gear^2, mtcars)
```
