### ISSUE TITLE
Documentation for `v0.1.0` and create a stable badge.

### ISSUE THREAD

**Issue by codetalker7** [xKDR/CRRao.jl#95]
Since the documentation CI was modified (#93) after the release of `v0.1.0`, Documenter couldn't build documentation for the release. So the documentation for this version will have to be manually built.

The section on [Documentation Versions](https://documenter.juliadocs.org/stable/man/hosting/#Documentation-Versions) contains some information about how broken release deployments can be fixed. If this doesn't work for us, then we'll have to manually build and push documentation to the `gh-pages` branch.

Also, a badge must be created pointing to the documentation for the current stable version.

**Comment by sourish-cmi** [comment]
Are you creating a PR?
